# Generated by Django 3.0.7 on 2022-01-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposal_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
