# Generated by Django 3.2.9 on 2022-01-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisors',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
