# Generated by Django 4.0.1 on 2022-01-10 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='abstract',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
