# Generated by Django 3.2.9 on 2022-01-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisors',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='group_id',
        ),
    ]
