# Generated by Django 4.0.1 on 2022-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0002_proposals_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='promotion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
