# Generated by Django 3.2.9 on 2022-01-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0003_alter_students_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_group',
            new_name='group',
        ),
    ]
