# Generated by Django 3.2.9 on 2022-01-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0005_alter_students_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksupervisor',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.studentgroups'),
        ),
        migrations.AddField(
            model_name='feedbacksupervisor',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.adminhod'),
        ),
        migrations.AlterField(
            model_name='feedbacksupervisor',
            name='supervisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.supervisors'),
        ),
    ]
