# Generated by Django 3.2.9 on 2022-01-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CST_SPMS', '0006_auto_20220111_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackgroup',
            name='studentgroup_id',
        ),
        migrations.RemoveField(
            model_name='feedbackhod',
            name='hod_id',
        ),
        migrations.AddField(
            model_name='feedbackgroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.studentgroups'),
        ),
        migrations.AddField(
            model_name='feedbackgroup',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.adminhod'),
        ),
        migrations.AddField(
            model_name='feedbackgroup',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.supervisors'),
        ),
        migrations.AddField(
            model_name='feedbackhod',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.studentgroups'),
        ),
        migrations.AddField(
            model_name='feedbackhod',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.adminhod'),
        ),
        migrations.AddField(
            model_name='feedbackhod',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CST_SPMS.supervisors'),
        ),
    ]
